config/routes.rb
Rails.application.routes.draw do
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
  get 'home/index'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get  'other_lab'          =>     'radiology_requests#other_lab'
  get  'lab_history'          =>     'radiology_requests#lab_history'
  get  'enter_results'          =>     'radiology_requests#enter_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'
  
  
   get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file 
   post 'import' => 'services_inventories#import', as: :import
  
  
  
  

end

app/models/order_request.rb
class OrderRequest < ActiveRecord::Base
end

app/controllers/order_requests_controller.rb
class OrderRequestsController < ApplicationController
  before_action :set_order_request, only: [:show, :edit, :update, :destroy]
  layout "doc_patients",:only => [ :order_records]
  # GET /order_requests
  # GET /order_requests.json
  def index
    @order_request = OrderRequest.new
    @order_requests = OrderRequest.joins("INNER JOIN patients ON patients.id = order_requests.patient_id
                    INNER JOIN users ON users.id = order_requests.user_id  INNER JOIN services_inventories ON services_inventories.id = order_requests.service_id").select('order_requests.id,services_inventories.service_name,surname,other_names,patients.mobile_number,card_no,fullname,occupation,address,dob,patients.user_id,order_requests.created_at,order_requests.patient_id,personnel_id,order_requests.status')
  end

  def order_records

    @assign_patient = AssignPatient.new
    @order_request = OrderRequest.new

    patient_id =params[:id]
    @patient_id = patient_id

    @patient_records = Patient.find_by(id: patient_id)

    @order_requests = OrderRequest.joins("INNER JOIN patients ON patients.id = order_requests.patient_id
                    INNER JOIN users ON users.id = order_requests.user_id INNER JOIN services_inventories ON services_inventories.id = order_requests.service_id").select('order_requests.status,order_requests.id,services_inventories.service_name,surname,other_names,patients.mobile_number,card_no,fullname,occupation,address,dob,patients.user_id,order_requests.created_at,order_requests.patient_id,personnel_id').where(patient_id: patient_id ).order('order_requests.id desc')

    respond_to do |format|

      format.html
      format.js
    end
  end

  def make_order

    # @assign_patient = AssignPatient.new
    @order_request = OrderRequest.new
    @lab_request = LabRequest.new

    patient_id=params[:id]
    @patient_id = patient_id

    logger.info "Lets see medical id #{@patient_id}"

    @services_inventories = ServicesInventory.order(:service_name).where("service_name like ?", "%#{params[:service_id]}" )
    @service_list = @services_inventories.map { |a|[a.service_name+" ",a.id]  }

    respond_to do |format|

      format.html
      format.js
    end
  end

  def view_order

    @assign_patient = AssignPatient.new
    patient_id=params[:id]

    # @document1 = OrderRequest.find_by(patient_id: patient_id)

    @document1 = OrderRequest.joins("INNER JOIN patients ON patients.id = order_requests.patient_id
                    INNER JOIN order_masters ON order_masters.id = order_requests.order_master_id").select('order_name').where(patient_id: patient_id )

    respond_to do |format|

      format.html
      format.js
    end
  end

  def close_order

    @order_request = OrderRequest.new

    @created_at = params[:id]
    logger.info "created_at: #{@created_at}"

    @order_id = OrderRequest.find_by(created_at: @created_at)
    @order_status = "true"
    logger.info "Order_status: #{@order_status}"
    logger.info "Order_id: #{@order_id.id}"
    logger.info "Order_status: #{@order_id.status}"
    logger.info "Created at: #{@order_id.created_at}"
    logger.info "Patient ID: #{@order_id.patient_id}"
    logger.info "Service ID: #{@order_id.service_id}"

  # OrderRequest.update(@order_id.id, :status => 1)

  end

  # GET /order_requests/1
  # GET /order_requests/1.json
  def show
  end

  # GET /order_requests/new
  def new
    @order_request = OrderRequest.new
  end

  # GET /order_requests/1/edit
  def edit
  end

  # POST /order_requests
  # POST /order_requests.json
  def create
    patient_id = params[:order_request][:patient_id]
    service_id = params[:order_request][:service_id]

    logger.info "------------------SERVICE ID #{service_id}-------------------------"
    @category = ServicesInventory.where(id: service_id)
    @category_id = @category[0].category_id

    
    @services_data = ServicesInventory.find_by(id: service_id)
    @price = @services_data.price

    if @category_id == 2

      if MedicationTemp.where(patient_id: patient_id).exists?
        @id = MedicationTemp.find_by(patient_id: patient_id)
        @medication_temp = MedicationTemp.update(@id.id, :created_at => Time.now )
      else
        @medication_temp = MedicationTemp.new({:patient_id => patient_id, :service_id => service_id,:status=> 0})
        @medication_temp.save
      end
      
      if BillTemp.where(patient_id: patient_id).exists?
        @id = BillTemp.find_by(patient_id: patient_id)
       @bills = BillHistory.new({:service_id => service_id,:patient_id => patient_id, :price => @price ,:status=> 0})
       @bills_temp = BillTemp.update(@id.id, :created_at => Time.now )
       @bills.save
      
      else
        @bills = BillHistory.new({:service_id => service_id,:patient_id => patient_id, :price => @price ,:status=> 0})
        @bills_temp = BillTemp.new({:patient_id => patient_id, :status=> 0})
        @bills.save
        @bills_temp.save
      end
          
    else
       if BillTemp.where(patient_id: patient_id).exists?
        @id = BillTemp.find_by(patient_id: patient_id)
       @bills = BillHistory.new({:service_id => service_id,:patient_id => patient_id, :price => @price ,:status=> 0})
       @bills_temp = BillTemp.update(@id.id, :created_at => Time.now )
       @bills.save
      
      else
        @bills = BillHistory.new({:service_id => service_id,:patient_id => patient_id, :price => @price ,:status=> 0})
        @bills_temp = BillTemp.new({:patient_id => patient_id, :status=> 0})
        @bills.save
        @bills_temp.save
      end
    end
    
    @order_request = OrderRequest.new(order_request_params)

    respond_to do |format|
   if @order_request.save
      format.html { redirect_to order_records_path(:id => patient_id), notice: 'Order request was successfully created.' }
      format.json { render :show, status: :created, location: @order_request }
    else
    format.html { render :new }
    format.json { render json: @order_request.errors, status: :unprocessable_entity }
    end
    end
  end

  # PATCH/PUT /order_requests/1
  # PATCH/PUT /order_requests/1.json
  def update
    respond_to do |format|
      if @order_request.update(order_request_params)
        format.html { redirect_to @order_request, notice: 'Order request was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_request }
      else
        format.html { render :edit }
        format.json { render json: @order_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_requests/1
  # DELETE /order_requests/1.json
  def destroy
    @order_request.destroy
    respond_to do |format|
      format.html { redirect_to order_requests_url, notice: 'Order request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order_request
    @order_request = OrderRequest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_request_params
    params.require(:order_request).permit(:patient_id, :user_id, :personnel_id, :status, :order_master_id, :service_id)
  end
end

app/helpers/order_requests_helper.rb
module OrderRequestsHelper
end

app/views/order_requests/_form.html.erb
<%= simple_form_for(@order_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :patient_id %>
    <%= f.input :user_id %>
    <%= f.input :personnel_id %>
    <%= f.input :status %>
    <%= f.input :order_master_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/order_requests/_make_order.html.erb
 <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <script src="/assets/bootstrap-combobox.js"></script>


   <div class="table-agile-info" role="form">

 
   <%= simple_form_for(@order_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 

                             


  <div class="form-group">
 
    <%#= f.input :personnel_id,label: "Lab Technician", collection: Role.where("id = 2"), label_method: :role_name, value_method: :id,class:'form-control'%>
  </div>


  <div class="form-inputs">
    <%= f.input :user_id, :as=> :hidden,input_html: {value: current_user.role_id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

</div>

<center>
  <div class="form-group">
 
      <%= f.input :service_id, label: "Select orders", collection:  @service_list,  label_method: :first, value_method: :last, input_html:{ class:"combobox form-control",data: { placeholder: "Order List" } }%>

  </div>
</center>

<div class="form-inputs">
  <% if (defined?(@patient_id)).nil? %>
    <%= f.input :patient_id,:as=> :hidden %>

   <% else  %>
  <%= f.input :patient_id, :as=> :hidden,input_html: {value: @patient_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>

  </div>

  <div class="form-inputs">
    <%= f.input :status, :as=> :hidden, input_html: {value: 0 } %>

  </div>

<center>

   <div class="form-actions">
    <%#= f.button :submit %>
     <%= f.submit "Make Order",:class => "btn btn-primary btn-sm" %>
  </div>
  </center>

<% end %>

<% end %>

</div>




<script type="text/javascript">
    $(document).ready(function(){
         $('form').attr('autocomplete', 'off');
        
         $('.combobox').combobox();

   $('span.input-group-addon').addClass("hidden");
  
    });
</script>

app/views/order_requests/_view_order.html.erb
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
 
        <table class="custab table table-striped table-hover table-bordered">
<br>
        
           
                             
<br>
<br>
               
               <div class="cent"  ><b><p>Order Requested</p></b></div>                 
        
           
              
          <!--   <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Order requested</td> -->
            <!-- <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"> -->
            <center>
                 <%=  @document1[0].order_name %>
              
            </center>
         
           <!--  </td> -->
             
        <!--   </tr> -->
          



 
          
        <% #end %>
          
         
           </table>
          
  </div>
</div>

app/views/order_requests/close_order.js.erb
<% if @order_id.status == true %>
    $(".order-<%= @order_id.id %> > a").html('cLose order').removeClass('btn-warning').addClass('btn-success')
<% else %>
    $(".order-<%= @order_id.id %> > a").html('Order cLosed').removeClass('btn-success').addClass('btn-success')
<% end %>
$("#order_status-status-<%= @order_id.id %>").html("<%= @order_id.status %>")

app/views/order_requests/edit.html.erb
<h1>Editing Order Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_request %> |
<%= link_to 'Back', order_requests_path %>

app/views/order_requests/index.html.erb
<section id="main-content">
  <section class="wrapper">
     
    <div class="table-agile-info">
 <div class="panel panel-default">
             
<br>
<br>
    <div class="panel-heading">
   Order Requests
    </div>
    
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr>

              <th data-breakpoints="xs">No</th> 
      
      <th>Patient No</th>
      <th>Name</th>
      <th>Order Name</th>
       <th>Status</th>
       <th>Date</th>
      <th>Created by</th>
       <th>status</th>
       
      
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>

          </tr>
        </thead>
        <tbody>
      <% count=1 %>

           <% @order_requests.each do |order| %>
      <tr>
         
        <td><%= count %></td> 
        
          <td><%= order.card_no%></td>
         <td><%= order.other_names + " " +  order.surname %></td>
           <td><%= order.service_name %></td>
         <td><%= "Ordered" %></td>
          <td><%= order.created_at %></td>
         <td><%= order.fullname %></td>
         


<td class="order-<%= order.id %>">
    <%= link_to "#{ order.status ? 'Closed' : 'Close Order' }", close_order_path(:id => order.created_at),{remote: :true, class: "btn btn-xs btn-#{ order.status  ? 'success' : 'warning' }"} %>
</td>

<!-- ,:data =>{disable_with:  "<i class='fa fa-refresh fa-spin'></i> Closing order..." } -->
    


<!--            <td id = "closed">
    <%#= link_to "#{ order.status ? 'Closed' : 'Close Order' }", close_order_path(:id => order.created_at), remote: :true, class: "btn btn-xs btn-#{ order.status ? 'success' : 'warning' }"  %>
</td> -->


      

       <% count=count+1 %> 
    <% end %>
       
           

        </tbody>
      </table>

       <center>

     </center>   

  </div>
</div>
</section>
 
</section>









<div id="myModal1" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Order Details</h4>
      </div>
      <div class="modal-body" id = 'boom2'>
      <%#= render "view_order" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/order_requests/make_order.js.erb
$("#boom").html("<%= escape_javascript(render 'order_requests/make_order') %>");
 $('#modal-window').modal('show');

app/views/order_requests/new.html.erb
<h1>New Order Request</h1>

<%= render 'form' %>

<%= link_to 'Back', order_requests_path %>

app/views/order_requests/order_records.html.erb
<section id="main-content">
  <section class="wrapper">
     
    <div class="table-agile-info">
 <div class="panel panel-default">
             
<br>
<br>
    <div class="panel-heading">
  Order Requests
    </div>
    
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr>

              <th data-breakpoints="xs">No</th> 
      
      <th>Patient No</th>
      <th>Name</th>
      <th>Order Name</th>
      
        <th>Status</th>
        <th>Date</th>
      <th>Created by</th>
       
      
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>

          </tr>
        </thead>
        <tbody>
      <% count=1 %>

           <% @order_requests.each do |order| %>
      <tr>
         
        <td><%= count %></td> 
        
          <td><%= order.card_no%></td>
         <td><%= order.other_names + " " +  order.surname %></td>
        <td><%= order.service_name %></td>
         
         <% if order.status == false %>
         <td><%= "Ordered" %></td>
          <%else %>
          <td><%= "Order closed" %></td>
           <%end %>
         <td><%= order.created_at %></td>
         <td><%= order.fullname %></td>

         <td class="order-<%= order.id %>">
    <%= link_to "#{ order.status ? 'Closed' : 'Close Order' }", close_order_path(:id => order.created_at),{remote: :true, class: "btn btn-xs btn-#{ order.status  ? 'success' : 'warning' }"} %>
</td>
      
      </tr>
       <% count=count+1 %> 
    <% end %>
       
           

        </tbody>
      </table>

       <center>

<% if current_user.role_id == 1 %>

 <%= link_to  'Make Order ', make_order_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>
 <% else%>
 <% end %>

     </center>   

  </div>
</div>
</section>
 
</section>






<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Make Order</h4>
      </div>
      <div class="modal-body" id = 'boom'>
      <%= render "make_order" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>





<div id="myModal1" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Order Details</h4>
      </div>
      <div class="modal-body" id = 'boom2'>
      <%#= render "view_order" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/order_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @order_request.patient_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @order_request.user_id %>
</p>

<p>
  <strong>Personnel:</strong>
  <%= @order_request.personnel_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order_request.status %>
</p>

<p>
  <strong>Order master:</strong>
  <%= @order_request.order_master_id %>
</p>

<%= link_to 'Edit', edit_order_request_path(@order_request) %> |
<%= link_to 'Back', order_requests_path %>

app/views/order_requests/view_order.js.erb
$("#boom2").html("<%= escape_javascript(render 'order_requests/view_order') %>");
$("#modal-window").html("<%= escape_javascript(render 'order_requests/view_order') %>");
 $('#modal-window').modal('show');