config/routes.rb
Rails.application.routes.draw do
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
  get 'home/index'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get  'other_lab'          =>     'radiology_requests#other_lab'
  get  'lab_history'          =>     'radiology_requests#lab_history'
  get  'enter_results'          =>     'radiology_requests#enter_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'
  
  
   get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file 
   post 'import' => 'services_inventories#import', as: :import
  
  
  
  

end

app/models/bill_temp.rb
class BillTemp < ActiveRecord::Base
end

app/controllers/bill_temps_controller.rb
class BillTempsController < ApplicationController
  before_action :set_bill_temp, only: [:show, :edit, :update, :destroy]
  # GET /bill_temps
  # GET /bill_temps.json
  def index
    #@bill_temps = BillTemp.all

    @bill_temps = BillTemp.joins("INNER JOIN patients ON patients.id = bill_temps.patient_id
                    ").select('surname,other_names,bill_temps.patient_id,bill_temps.created_at').order('bill_temps.created_at desc')
  end

  def bill_open

    @assign_patient = AssignPatient.new
    patient_id=params[:id]

    # @bills = BillHistory.where(patient_id: patient_id)

    @bill_histories = BillHistory.joins("INNER JOIN patients ON patients.id = bill_histories.patient_id
                    INNER JOIN services_inventories ON services_inventories.id = bill_histories.service_id").select('bill_histories.id,surname,other_names,bill_histories.price,bill_histories.quantity,service_name,bill_histories.patient_id,bill_histories.created_at,bill_histories.status').where(patient_id: patient_id)

    @bill_total = BillHistory.where(patient_id: patient_id, status: 0)
    @total = @bill_total.sum(:price)

    logger.info "PRICE IS #{@total}"
    # logger.info "record: #{@record.inspect}"

    respond_to do |format|

      format.html
      format.js
    end
  end

  def outstanding
  
    @bill_history_id = params[:id]
    
    @bill_id = BillHistory.find_by(id: @bill_history_id)
    @bill_status = "true"
    BillHistory.update(@bill_history_id, :status => 1)
    
  end

  def paid
    bill_history_id =params[:id]
    if BillHistory.update(bill_history_id, :status => 0)
      redirect_to bill_temps_path, notice: 'Bills has not been paid'
    end
  end


  def print_all_bill

    patient_id=params[:id]

    @bill_histories = BillHistory.joins("INNER JOIN patients ON patients.id = bill_histories.patient_id
                    INNER JOIN services_inventories ON services_inventories.id = bill_histories.service_id").select('bill_histories.id,surname,other_names,bill_histories.price,bill_histories.quantity,service_name,bill_histories.patient_id,bill_histories.created_at,bill_histories.status').where(patient_id: patient_id)

    logger.info "BILL HISTOURES #{@bill_histories.inspect}"
    
    @bill_total = BillHistory.where(patient_id: patient_id, status: 1)
    @total = @bill_total.sum(:price)
     logger.info "PRICE IS #{@total}"

    respond_to do |format|

      format.html

      format.pdf do
        pdf = AllBills.new(@bill_histories)
        #pdf.text "HIIIII"
        send_data pdf.render, filename: "Totalbills.pdf",
                                type: "application/pdf",
                                dispostion: "inline"
      end
    end
  end






   def print_bill

    
    bill_id=params[:id]

    # @documents = BillHistory.find_by(id: @bill_history_id)
    @bill_histories = BillHistory.joins("INNER JOIN patients ON patients.id = bill_histories.patient_id
                    INNER JOIN services_inventories ON services_inventories.id = bill_histories.service_id").select('bill_histories.id,surname,other_names,bill_histories.price,bill_histories.quantity,service_name,bill_histories.patient_id,bill_histories.created_at,bill_histories.status').where(id: bill_id)

  logger.info "BILL HISTOURES #{@bill_histories.inspect}"
  
    respond_to do |format|

      format.html

      format.pdf do
        pdf = PatientBillPdf.new(@bill_histories)
        #pdf.text "HIIIII"
        send_data pdf.render, filename: "bills.pdf",
                                type: "application/pdf",
                                dispostion: "inline"
      end
    end
  end



  # GET /bill_temps/1
  # GET /bill_temps/1.json
  def show
  end

  # GET /bill_temps/new
  def new
    @bill_temp = BillTemp.new
  end

  # GET /bill_temps/1/edit
  def edit
  end

  # POST /bill_temps
  # POST /bill_temps.json
  def create
    @bill_temp = BillTemp.new(bill_temp_params)

    respond_to do |format|
      if @bill_temp.save
        format.html { redirect_to @bill_temp, notice: 'Bill temp was successfully created.' }
        format.json { render :show, status: :created, location: @bill_temp }
      else
        format.html { render :new }
        format.json { render json: @bill_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_temps/1
  # PATCH/PUT /bill_temps/1.json
  def update
    respond_to do |format|
      if @bill_temp.update(bill_temp_params)
        format.html { redirect_to @bill_temp, notice: 'Bill temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_temp }
      else
        format.html { render :edit }
        format.json { render json: @bill_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_temps/1
  # DELETE /bill_temps/1.json
  def destroy
    @bill_temp.destroy
    respond_to do |format|
      format.html { redirect_to bill_temps_url, notice: 'Bill temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bill_temp
    @bill_temp = BillTemp.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bill_temp_params
    params.require(:bill_temp).permit(:patient_id, :user_id, :status)
  end
end

app/helpers/bill_temps_helper.rb
module BillTempsHelper
end

app/views/bill_temps/_bill_open.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-1">
		<table class="custab table table-striped table-hover table-bordered">

			<br>

			<br>
			<br>

			<div>
				<table class="table" ui-jq="footable" ui-options='{
				"paging": {
				"enabled": true
				},
				"filtering": {
				"enabled": true
				},
				"sorting": {
				"enabled": true
				}}'>
					<thead>
						<tr>
							<th>Patient</th>
							<th>Service</th>
							<!-- <th>Quantity / Days</th> -->
							<th>Price(GHc)</th>
							<th>Date</th>
							<th>Status</th>

							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<% @bill_histories.each do |bill_history| %>
						<tr>

							<td><%= bill_history.other_names + " " + bill_history.surname %></td>
							<td><%= bill_history.service_name %></td>
							<!-- <td><%= bill_history.quantity %></td> -->
							<td><%= bill_history.price %></td>
							<td><%= bill_history.created_at %></td>

							<% if current_user.role_id == 8 %>

							<td class="bill_history-<%= bill_history.id %>"> <%= link_to "#{ bill_history.status ? 'Paid' : 'Oustanding' }", outstanding_path(:id => bill_history.id),{remote: :true, class: "btn btn-xs btn-#{ bill_history.status  ? 'success' : 'warning' }"} %> </td>
							<% else%>

							<td <%= bill_history.id %>"> <%= "#{ bill_history.status ? 'Paid' : 'Oustanding' }" %> </td>

							<% end %>
							
							<td><%= link_to 'Print', print_bill_path(:id => bill_history.id, format: "pdf" ) %></td>
						</tr>

						<% end %>
					</tbody>
				</table>

				<%= 'Amount Due = GHC ' %>
				<%= @total  %>
				<br>

			</div>

	</div>
</div>

<center>

	<%= link_to 'Print All' , print_all_bill_path(:id => @bill_histories[0].patient_id, format: "pdf" ) %>
 

</center>

app/views/bill_temps/_form.html.erb
<%= simple_form_for(@bill_temp) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :patient_id %>
    <%= f.input :user_id %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bill_temps/bill_open.js.erb
$("#hi").html("<%= escape_javascript(render 'bill_temps/bill_open') %>");
$("#modal-window").html("<%= escape_javascript(render 'bill_temps/bill_open') %>");
 $('#modal-window').modal('show');

app/views/bill_temps/edit.html.erb
<h1>Editing Bill Temp</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_temp %> |
<%= link_to 'Back', bill_temps_path %>

app/views/bill_temps/index.html.erb
<section id="main-content">
  <section class="wrapper">
     
    <div class="table-agile-info">
 <div class="panel panel-default">

   <div class="panel-heading">
   Bills 
    </div>
    
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
    <tr>
      
      <th>Patient</th>
      <th>Date</th>
     
     
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_temps.each do |bill_history| %>
      <tr>
        
        <td><%= link_to bill_history.other_names.upcase + " " + bill_history.surname.upcase , bill_open_path(:id => bill_history.patient_id),{:remote => true,'data-toggle' =>  "modal",'data-target' => '#myModal'} %></td>
         <td><%= bill_history.created_at %></td>
       
        
    
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  </div>
</div>
</section>
 
</section>


<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Bill History</h4>
      </div>
      <div class="modal-body" id = 'hi'>
      <%#= render "assign_lab" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/bill_temps/new.html.erb
<h1>New Bill Temp</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_temps_path %>

app/views/bill_temps/outstanding.js.erb
<% if @bill_id.status == true %>
    $(".bill_history-<%= @bill_id.id %> > a").html('Outstanding').removeClass('btn-warning').addClass('btn-success')
<% else %>
    $(".bill_history-<%= @bill_id.id %> > a").html('Paid').removeClass('btn-success').addClass('btn-success')
<% end %>
$("#bill_status-status-<%= @bill_id.id %>").html("<%= @bill_id.status %>")

app/views/bill_temps/print_bill.html.erb
<section id="main-content">
	<section class="wrapper">

		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<table class="custab table table-striped table-hover table-bordered">

					<div  >
						<b>
						<p>
							BILL Results
						</p></b>
					</div>

					<td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Test Results</td>
					<td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%#=.results%></td>

					</tr>
					<tr>

				</table>

			</div>
		</div>

	</section>
</section >

app/views/bill_temps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @bill_temp.patient_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @bill_temp.user_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bill_temp.status %>
</p>

<%= link_to 'Edit', edit_bill_temp_path(@bill_temp) %> |
<%= link_to 'Back', bill_temps_path %>