config/routes.rb
Rails.application.routes.draw do
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
  get 'home/index'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get  'other_lab'          =>     'radiology_requests#other_lab'
  get  'lab_history'          =>     'radiology_requests#lab_history'
  get  'enter_results'          =>     'radiology_requests#enter_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'
  
  
   get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file 
   post 'import' => 'services_inventories#import', as: :import
  
  
  
  

end

app/models/assign_patient.rb
class AssignPatient < ActiveRecord::Base



	   belongs_to :patients, class_name: 'Patient', foreign_key: :patient_id
	   belongs_to :a_user, class_name: 'User', foreign_key: :user_id
end

app/controllers/assign_patients_controller.rb
class AssignPatientsController < ApplicationController
  before_action :set_assign_patient, only: [:show, :edit, :update, :destroy]

  layout "doc_patients",:only => [ :docs]
  # :only => [ :show, :edit, :update, :destroy]
  # GET /assign_patients
  # GET /assign_patients.json
  def index

    @vital_record = BasicMedRecord.new
    #@assign_patients = AssignPatient.joins(:patients).select('surname,other_names,mobile_number,occupation,address,dob,patients.user_id').group('patient_id').where(nurse_id: current_user.id )
    @clinic_document = ClinicDocument.new

    @assign_patients= AssignPatient.joins("INNER JOIN patients ON patients.id = assign_patients.patient_id
                  INNER JOIN users ON users.id = assign_patients.user_id").select('surname,other_names,patients.mobile_number,fullname,occupation,address,dob,patients.user_id,patient_id,assign_patients.id,assign_patients.status,basic_medical_record_id,personnel_id,users.role_id,card_no,assign_patients.created_at').where(personnel_id: current_user.role_id).order('id desc')

    @assign_to_doctor = AssignPatient.new
    @assign_patient = AssignPatient.new
    @lab_request = LabRequest.new
    @medication_request = MedicationRequest.new

  end

  # GET /assign_patients/1
  # GET /assign_patients/1.json
  def show
  end

  # GET /assign_patients/new
  def new
    @assign_patient = AssignPatient.new

    @patient = Patient.find(params[:id])

    session[:return_to] ||= request.referer
    @record = Patient.find_by(id: patient_id)

    logger.info "Lets see the records"
    logger.info "record: #{@record.inspect}"
    logger.info "patient id: #{@record.id}"
    p "record: #{@record.inspect}"
    logger.info "---------------------------------------------"
    logger.info "---------------------------------------------"
    @patient = Patient.new
  end

  # GET /assign_patients/1/edit
  def edit
  end

  def show_details
    patient_id=params[:id]

    @patients1 = Patient.find_by(id: patient_id)
    logger.info "patients1: #{@patients1}"
    @patients1.other_names
    logger.info "other_names: #{@patients1.other_names}"
  end

  def basic_medical
    @vital_record = BasicMedRecord.new
    @created_at=params[:id]

    logger.info "Lets see id para #{@created_at}"
    patient_record = AssignPatient.find_by(created_at: @created_at)
    @patient_id =  patient_record.patient_id
    logger.info "Lets see the patient id in basic medical is #{@patient_id}"

    @assign_patient = AssignPatient.new

    respond_to do |format|

      format.html
      format.js
    end
  end
  
  def basic_vitals
   @vital_record = BasicMedRecord.new
 
   patient_id  = params[:basic_med_record][:patient_id]
   blood_pressure  = params[:basic_med_record][:blood_pressure]
   pulse  = params[:basic_med_record][:pulse]
   temp  = params[:basic_med_record][:temp]
   respiratory_rate  = params[:basic_med_record][:respiratory_rate]
   user_id  = params[:basic_med_record][:user_id]
   status  = params[:basic_med_record][:status]
   complaints  = params[:basic_med_record][:complaints]
   admission_status  = params[:basic_med_record][:admission_status]
   @info = BasicMedRecord.new({:patient_id => patient_id,:blood_pressure => blood_pressure,:pulse => pulse,:temp => temp,:respiratory_rate => respiratory_rate,:user_id => user_id,:status => status,:complaints => complaints, :admission_status => admission_status})
   @info.save
   
   respond_to do |format|
      
        format.html { redirect_to basic_med_records_path, notice: 'Patient Vitals Taken Successfully ' }
        format.js
    end
    
  end
  
  

  def clinic_documentation

    @assign_patient = AssignPatient.new
    @clinic_document = ClinicDocument.new

    patient_id=params[:id]
    @patient_id = patient_id

    logger.info "Lets see medical id #{@patient_id}"

    @b_records = BasicMedRecord.find_by(patient_id: patient_id)

    @blood_pressure = @b_records.blood_pressure
    @pulse = @b_records.pulse
    @respiratory = @b_records.respiratory_rate
    @temperature = @b_records.temp
    @patient_id = @b_records.patient_id
    @complaints = @b_records.complaints

    @vital_signs = "Respiratory Rate: " + @b_records.respiratory_rate + " " + "Pulse: " +  @b_records.pulse + " " + "Blood Pressure: " +  @b_records.blood_pressure + " " + "Temperature: " +  @b_records.temp

    logger.info "Vital signs: #{@vital_signs}"

    if (defined?(@b_records)).nil?
      @ass_p_records = AssignPatient.find_by(patient_id: patient_id)

      AssignPatient.update(@ass_p_records.id, :status => 1)

      logger.info "------------------------------------------"
      logger.info "Lets see the b records"
      logger.info "basic medical record: #{@b_records.inspect}"
      logger.info "------------------------------------------"

      @blood_pressure = @b_records.blood_pressure
      @pulse = @b_records.pulse
      @respiratory = @b_records.respiratory_rate
      @temperature = @b_records.temp
      @patient_id = @b_records.patient_id

      patient_id = @patient_id

      @basic_med_id = @b_records.id
      basic_med_id = @basic_med_id
      logger.info "patient id: #{@patient_id}"
      logger.info " basic_med_id: #{@basic_med_id}"
      logger.info "   @b_records.blood_pressure: #{ @blood_pressure}"

    else

      logger.info " LIEEEEESSSSS"

    end

    respond_to do |format|

      format.js
      format.html
    end
  end

  def view_documentation

    @assign_patient = AssignPatient.new
    created_at=params[:id]

    @documents = ClinicDocument.where(created_at: created_at)
    logger.info "document1: #{@documents.inspect}"

    respond_to do |format|

      format.html
      format.js
    end

  end

  def assign_lab
    @assign_patient = AssignPatient.new
    @lab_request = LabRequest.new
    basic_med_id=params[:id]

    @b_records = BasicMedRecord.find_by(id: basic_med_id)

    @patient_id = @b_records.patient_id
    patient_id = @patient_id

    @basic_med_id = @b_records.id
    basic_med_id = @basic_med_id

    respond_to do |format|

      format.html
      format.js
    end

  end

  def assign_med
    @assign_patient = AssignPatient.new
    @medication_request = MedicationRequest.new
    basic_med_id=params[:id]

    @b_records = BasicMedRecord.find_by(id: basic_med_id)

    @patient_id = @b_records.patient_id
    patient_id = @patient_id

    @basic_med_id = @b_records.id
    basic_med_id = @basic_med_id

    respond_to do |format|

      format.html
      format.js
    end
  end

  def docs

    @assign_patient = AssignPatient.new
    @clinic_document = ClinicDocument.new

    patient_id =params[:id]
    @patient_id = patient_id

    @patient_records = Patient.find_by(id: patient_id)

    logger.info "Lets see patient_id id #{@patient_id}"
    logger.info "Lets see  Patient name #{@patient_records.surname } #{@patient_records.other_names }"
    if (defined?(patient_id)).nil?

      @b_records = BasicMedRecord.find_by(patient_id: patient_id)
      @blood_pressure = @b_records.blood_pressure
      @pulse = @b_records.pulse
      @respiratory = @b_records.respiratory_rate
      @temperature = @b_records.temp
      @patient_id = @b_records.patient_id

      patient_id = @patient_id

      @basic_med_id = @b_records.id
      basic_med_id = @basic_med_id

      logger.info "Lets see medical id #{patient_id}"

      @clinic_documents = ClinicDocument.joins("INNER JOIN patients ON patients.id = clinic_documents.patient_id
                    INNER JOIN users ON users.id = clinic_documents.user_id INNER JOIN basic_med_records ON basic_med_records.id = clinic_documents.basic_medical_record_id").select('surname,other_names,patients.mobile_number,blood_pressure,pulse,temp,respiratory_rate,fullname,occupation,address,dob,patients.user_id,basic_med_records.id,complaints,symptoms,vital_signs,clinic_exams,final_diagnosis,investigations,treatment_plans,card_no,clinic_documents.created_at,clinic_documents.patient_id,clinic_documents.id').where(patient_id: patient_id,status: 1 ).order('id desc')

      logger.info "CLINIC DOCUMENTS: #{@clinic_documents}"

      @document1 = ClinicDocument.find_by(id: patient_id)
      logger.info "document1: #{@document1}"
      logger.info "complaints: #{@document1.complaints}"

    else

      logger.info "XXXXXXXXXXXXXXXXXXXXXX"

      @clinic_documents = ClinicDocument.joins("INNER JOIN patients ON patients.id = clinic_documents.patient_id
                    INNER JOIN users ON users.id = clinic_documents.user_id").select('surname,other_names,patients.mobile_number,fullname,occupation,address,dob,patients.user_id,complaints,symptoms,vital_signs,clinic_exams,final_diagnosis,investigations,treatment_plans,card_no,clinic_documents.created_at,clinic_documents.patient_id,clinic_documents.id').where(patient_id: patient_id ,status: 1).order('id desc')

    end

    respond_to do |format|

      format.html
      format.js
    end

  end

  def assign_to_a_doctor
    logger.info "---------------------------ASSIGED DOCTOR---------------------------------"

    personnel_id = params[:assign_patient][:personnel_id]
    patient_id = params[:assign_patient][:patient_id]
    role_id = params[:assign_patient][:role_id]
    user_id = params[:assign_patient][:user_id]
    status = params[:assign_patient][:status]
    basic_medical_record_id = params[:assign_patient][:basic_medical_record_id]

    if personnel_id == '1'

      service_id = 4
      @services_data = ServicesInventory.find_by(id: service_id)
      price = @services_data.price
    
    if BillTemp.where(patient_id: patient_id).exists?
      @id = BillTemp.find_by(patient_id: patient_id)
      @bills = BillHistory.new({:service_id => service_id,:patient_id => patient_id, :price => price ,:status=> 0})
      @bills_temp = BillTemp.update(@id.id, :created_at => Time.now )
      @bills.save

    else
      @bills = BillHistory.new({:service_id => service_id,:patient_id => patient_id, :price => price ,:status=> 0})

app/helpers/assign_patients_helper.rb
module AssignPatientsHelper
end

app/views/assign_patients/_assign_lab.html.erb
<!-- <body> -->
  <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css"> -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

   <div class="table-agile-info" role="form">

 
   <%= simple_form_for(@lab_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 

                             


  <div class="form-group">
 
    <%= f.input :personnel_id,label: "Lab Technician", collection: User.where("role_id = 2"), label_method: :fullname, value_method: :id,class:'form-control'%>
  </div>


  <div class="form-inputs">
    <%= f.input :user_id, :as=> :hidden,input_html: {value: current_user.role_id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

</div>

<div class="form-group">

    <%= f.input :lab_type, label: "Lab type", as: :string, input_html: { class: 'form-control' } %>
  </div>

<div class="form-inputs">
  <% if (defined?(@patient_id)).nil? %>
    <%= f.input :patient_id,:as=> :hidden %>

   <% else  %>
  <%= f.input :patient_id, :as=> :hidden,input_html: {value: @patient_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>

  </div>

   <div class="form-inputs">
  <% if (defined?(@basic_med_id)).nil? %>
    <%= f.input :basic_medical_record_id,:as=> :hidden %>
   <% else  %>
  <%= f.input :basic_medical_record_id, :as=> :hidden,input_html: {value: @basic_med_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>
<% end %>
  </div>

 




  <div class="form-inputs">
    <%= f.input :status, :as=> :hidden, input_html: {value: 0 } %>

  </div>

<center>

   <div class="form-actions">
    <%#= f.button :submit %>
     <%= f.submit "Request Lab",:class => "btn btn-primary btn-sm" %>
  </div>
  </center>

<% end %>

<% end %>

</div>





<script type="text/javascript">
        $(function() {
        $('#datetimepicker6').datetimepicker({
        format : 'YYYY-MM-D H:m:s'
        });
        $("#datetimepicker6").on("dp.change", function(e) {
        $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        });

        $(document).ready(function() {
        $("#sent_status").show();
        });
        
       
        
</script>


<!-- <form role="form">
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Email address</label>
                                                <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Enter email">
                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputPassword1">Password</label>
                                                <input type="password" class="form-control" id="exampleInputPassword3" placeholder="Password">
                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputFile">File input</label>
                                                <input type="file" id="exampleInputFile3">
                                                <p class="help-block">Example block-level help text here.</p>
                                            </div>
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox"> Check me out
                                                </label>
                                            </div>
                                            <button type="submit" class="btn btn-default">Submit</button>
                                        </form> -->

app/views/assign_patients/_assign_med.html.erb
<!-- <body> -->
  <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css"> -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

   <div class="table-agile-info">

 
   <%= simple_form_for(@medication_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<!--   <div class="container">
        <fieldset>
                <div class="row">
                        <div class="col-md-5">
                         <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token.to_s %>"> -->

                             


  <div class="ggg">
 
    <%= f.input :personnel_id,label: "Pharmacist", collection: User.where("role_id = 5"), label_method: :fullname, value_method: :id,class: "ggg" %>
  </div>


  <div class="form-inputs">
    <%= f.input :user_id, :as=> :hidden,input_html: {value: current_user.role_id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

</div>

<div >

    <%= f.input :medication, label: "Medication", as: :string, input_html: {  } %>
  </div>

<div class="form-inputs">
  <% if (defined?(@patient_id)).nil? %>
    <%= f.input :patient_id,:as=> :hidden %>

   <% else  %>
  <%= f.input :patient_id, :as=> :hidden,input_html: {value: @patient_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>

  </div>

   <div class="form-inputs">
  <% if (defined?(@basic_med_id)).nil? %>
    <%= f.input :basic_medical_record_id,:as=> :hidden %>
   <% else  %>
  <%= f.input :basic_medical_record_id, :as=> :hidden,input_html: {value: @basic_med_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>
<% end %>
  </div>

 




  <div class="form-inputs">
    <%= f.input :status, :as=> :hidden, input_html: {value: 0 } %>

  </div>


<center>

   <div class="form-actions">
    <%#= f.button :submit %>
     <%= f.submit "Request Medication",:class => "btn btn-primary btn-sm" %>
  </div>
  </center>
<% end %>

<% end %>

</div>





<script type="text/javascript">
        $(function() {
        $('#datetimepicker6').datetimepicker({
        format : 'YYYY-MM-D H:m:s'
        });
        $("#datetimepicker6").on("dp.change", function(e) {
        $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        });

        $(document).ready(function() {
        $("#sent_status").show();
        });
        
       
        
</script>

app/views/assign_patients/_form.html.erb
<%= simple_form_for(@assign_patient) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :patient_id %>
    <%= f.input :role_id %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/assign_patients/docs.html.erb
<section id="main-content">
  <section class="wrapper">
     
    <div class="table-agile-info">
 <div class="panel panel-default">
  
    <div class="row">
     <% if (defined?(@blood_pressure)).nil? %>
 
   <% else  %>
    <div class="column"  ><p>Blood Pressure: <%= @blood_pressure %></p></div>
  <div class="column"><p>Respiratory Rate: <%= @respiratory %></p> </div>
    <div class="column"><p>Pulse: <%= @pulse %></p> </div>
  <div class="column"> <p>Temperature: <%= @temperature %></p> </p> </div>
  <% end %>
</div>

 <div class="row">
     <% if (defined?(@patient_records)).nil? %>
 
   <% else  %>
    <div class="column"  ><p>Name: <%= @patient_records.other_names + " " + @patient_records.surname %></p></div>
  <div class="column"><p>Patient No: <%= @patient_records.card_no %></p> </div>
    <div class="column"><p>Occupation: <%= @patient_records.occupation %></p> </div>
  <div class="column"> <p>Address: <%= @patient_records.address %></p> </p> </div>
  <div class="column"> <p>Mobile Number: <%= @patient_records.mobile_number %></p> </p> </div>
  <div class="column"> <p>Date of Birth: <%= @patient_records.dob %></p> </p> </div>
  <% end %>
</div>
                             
<br>
<br>
    <div class="panel-heading">
  Clinic documents
    </div>
    
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr>

              <th data-breakpoints="xs">No</th> 
      
    <!--   <th>Patient No</th>
      <th>Name</th> -->
      <th>Date </th>
      <th>Created by</th>
       
      
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>

          </tr>
        </thead>
        <tbody>
      <% count=1 %>

           <% @clinic_documents.each do |patient| %>
      <tr>
         
        <td><%= count %></td> 
        
          <!-- <td><%#= patient.card_no%></td>
         <td><%#= patient.other_names + " " +  patient.surname %></td> -->
      
         <td><%= patient.created_at %></td>
         <td><%= patient.fullname %></td>
         
          <td ><%= link_to 'View Documents', view_documentation_path(:id => patient.created_at),{:remote => true, class:'"btn btn-warning btn-sm btn3d"','data-toggle' =>  "modal",'data-target' => '#myModal1'} %></td> 
         
       
      </tr>
       <% count=count+1 %> 
    <% end %>
       
           

        </tbody>
      </table>

      

<% if current_user.role_id == 3 %>

<%else%>
 <center>
 <%= link_to  'New Clinic Documents', clinic_documentation_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>

     </center>   
<%end%>
  </div>
</div>
</section>
 
</section>




<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Clinic Document</h4>
      </div>
      <div class="modal-body" id = 'fii'>
      <%= render "clinic_documentation" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>


<div id="myModal1" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Clinic Document Details</h4>
      </div>
      <div class="modal-body" id = 'fi'>
      <%= render "view_documentation" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/assign_patients/edit.html.erb
<h1>Editing Assign Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @assign_patient %> |
<%= link_to 'Back', assign_patients_path %>

app/views/assign_patients/new.html.erb
<h1>New Assign Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', assign_patients_path %>

app/views/assign_patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @assign_patient.patient_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @assign_patient.role_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @assign_patient.status %>
</p>

<%= link_to 'Edit', edit_assign_patient_path(@assign_patient) %> |
<%= link_to 'Back', assign_patients_path %>