config/routes.rb
Rails.application.routes.draw do
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
  get 'home/index'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get  'other_lab'          =>     'radiology_requests#other_lab'
  get  'lab_history'          =>     'radiology_requests#lab_history'
  get  'enter_results'          =>     'radiology_requests#enter_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'
  
  
   get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file 
   post 'import' => 'services_inventories#import', as: :import
  
  
  
  

end

app/models/lab_order_list.rb
class LabOrderList < ActiveRecord::Base
  


end

app/controllers/lab_order_lists_controller.rb
class LabOrderListsController < ApplicationController
  before_action :set_lab_order_list, only: [:show, :edit, :update, :destroy]

  # GET /lab_order_lists
  # GET /lab_order_lists.json
  def index
    @lab_order_lists = LabOrderList.all
    @lab_order_list = LabOrderList.new
  end

  # GET /lab_order_lists/1
  # GET /lab_order_lists/1.json
  def show
  end

  # GET /lab_order_lists/new
  def new
    @lab_order_list = LabOrderList.new
  end
  
 

  # GET /lab_order_lists/1/edit
  def edit
  end

  # POST /lab_order_lists
  # POST /lab_order_lists.json
  def create
    @lab_order_list = LabOrderList.new(lab_order_list_params)

    respond_to do |format|
      if @lab_order_list.save
        format.html { redirect_to @lab_order_list, notice: 'Lab order list was successfully created.' }
        format.json { render :show, status: :created, location: @lab_order_list }
      else
        format.html { render :new }
        format.json { render json: @lab_order_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lab_order_lists/1
  # PATCH/PUT /lab_order_lists/1.json
  def update
    respond_to do |format|
      if @lab_order_list.update(lab_order_list_params)
        format.html { redirect_to @lab_order_list, notice: 'Lab order list was successfully updated.' }
        format.json { render :show, status: :ok, location: @lab_order_list }
      else
        format.html { render :edit }
        format.json { render json: @lab_order_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lab_order_lists/1
  # DELETE /lab_order_lists/1.json
  def destroy
    @lab_order_list.destroy
    respond_to do |format|
      format.html { redirect_to lab_order_lists_url, notice: 'Lab order list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lab_order_list
      @lab_order_list = LabOrderList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lab_order_list_params
      params.require(:lab_order_list).permit(:lab_name, :price, :status)
    end
end

app/helpers/lab_order_lists_helper.rb
module LabOrderListsHelper
end

app/views/lab_order_lists/_form.html.erb
<%= simple_form_for(@lab_order_list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :lab_name %>
    <%= f.input :price %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lab_order_lists/edit.html.erb
<h1>Editing Lab Order List</h1>

<%= render 'form' %>

<%= link_to 'Show', @lab_order_list %> |
<%= link_to 'Back', lab_order_lists_path %>

app/views/lab_order_lists/index.html.erb
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
			<div class="panel panel-default">
				<div class="panel-heading">

				</div>
				<div class="panel-body">
					<div class="position-center">
						
						<div>

							<table class="table" ui-jq="footable" ui-options='{
							"paging": {
							"enabled": true
							},
							"filtering": {
							"enabled": true
							},
							"sorting": {
							"enabled": true
							}}'>
								<thead>
									<tr>
										<th>Lab name</th>
										<th>Price</th>
										
										<th colspan="3"></th>
									</tr>
								</thead>

								<tbody>
									<% @lab_order_lists.each do |lab_order_list| %>
									<tr>
										<td><%= lab_order_list.lab_name %></td>
										<td><%= lab_order_list.price %></td>
										
										<td><%= link_to 'Show', lab_order_list %></td>
										<td><%= link_to 'Edit', edit_lab_order_list_path(lab_order_list) %></td>
										<td><%= link_to 'Destroy', lab_order_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
									</tr>
									<% end %>
								</tbody>
							</table>

							<br>

							<%= link_to 'New Lab order list', new_lab_order_list_path %>

						</div>
					</div>
				</div>
	</section>

</section>

app/views/lab_order_lists/new.html.erb
<h1>New Lab Order List</h1>

<%= render 'form' %>

<%= link_to 'Back', lab_order_lists_path %>

app/views/lab_order_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lab name:</strong>
  <%= @lab_order_list.lab_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @lab_order_list.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lab_order_list.status %>
</p>

<%= link_to 'Edit', edit_lab_order_list_path(@lab_order_list) %> |
<%= link_to 'Back', lab_order_lists_path %>